name: steve1
channels:
  - conda-forge
  - nvidia
  - defaults
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - aom=3.9.1=hac33072_0
  - attr=2.5.2=h39aace5_0
  - av=16.0.1=py310h07043f6_0
  - backports.zstd=1.1.0=py310h69bd2ac_1
  - blas=1.0=mkl
  - brotli-python=1.2.0=py310hba01987_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - cpython=3.10.19=py310hd8ed1ab_2
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=13.1=hd92462c_3
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - ffmpeg=8.0.0=gpl_hbbdf940_906
  - filelock=3.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gdk-pixbuf=2.44.4=h2b0a6b4_0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - glslang=16.0.0=hfd11570_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310h63ebcad_2
  - graphite2=1.3.14=hecca717_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.2.0=h15599e2_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - intel-gmmlib=22.8.2=hb700be7_0
  - intel-media-driver=25.3.4=hecca717_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - jinja2=3.1.6=pyhcf101f3_1
  - lame=3.100=h166bdaf_1003
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.45=h1aa0949_0
  - lerc=4.0.0=h0aef613_1
  - level-zero=1.26.0=hb700be7_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libass=0.17.4=h96ad9f0_0
  - libblas=3.9.0=16_linux64_mkl
  - libcap=2.77=h3ff7636_0
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.16.0.49=h3b4bcfc_0
  - libcurand=10.4.1.34=h5dabb87_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.1=h32235b2_2
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libhwloc=2.12.1=default_h7f8ec31_1002
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - libnpp=11.8.0.86=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvjpeg=11.9.0.86=0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopenvino=2025.2.0=hb617929_1
  - libopenvino-auto-batch-plugin=2025.2.0=hed573e4_1
  - libopenvino-auto-plugin=2025.2.0=hed573e4_1
  - libopenvino-hetero-plugin=2025.2.0=hd41364c_1
  - libopenvino-intel-cpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-gpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-npu-plugin=2025.2.0=hb617929_1
  - libopenvino-ir-frontend=2025.2.0=hd41364c_1
  - libopenvino-onnx-frontend=2025.2.0=h1862bb8_1
  - libopenvino-paddle-frontend=2025.2.0=h1862bb8_1
  - libopenvino-pytorch-frontend=2025.2.0=hecca717_1
  - libopenvino-tensorflow-frontend=2025.2.0=h0767aad_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hecca717_1
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libprotobuf=6.31.1=h49aed37_2
  - librsvg=2.60.0=h61e6d4b_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libsystemd0=258.2=h6569c3e_1
  - libtiff=4.7.1=h9d88235_1
  - libudev1=258.2=h6569c3e_1
  - libunwind=1.8.3=h65a8314_0
  - liburing=2.12=hb700be7_0
  - libusb=1.0.29=h73b1eb8_0
  - libuuid=2.41.2=he9a06e4_0
  - libva=2.22.0=h4f16b4b_2
  - libvorbis=1.3.7=h54a6638_2
  - libvpl=2.15.0=h54a6638_1
  - libvpx=1.14.1=hac33072_0
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.0=hca5e8e5_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=15.0.7=h0cdce71_0
  - markupsafe=3.0.3=py310h3406613_0
  - mkl=2022.1.0=hc2b9512_224
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpg123=1.32.9=hc50e24c_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - networkx=3.4.2=pyh267e887_2
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.6.0=hc22cd8d_0
  - openjdk=8.0.412=h2b85faf_2
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.6.0=h26f9b46_0
  - pango=1.56.4=hadf4263_0
  - pcre2=10.46=h1321c63_0
  - pillow=12.0.0=py310h80abafc_0
  - pixman=0.46.4=h54a6638_1
  - pkg-config=0.29.2=h4bc722e_1009
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=h9a6aba3_3
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.19=h3c07f61_2_cpython
  - python_abi=3.10=8_cp310
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cpu
  - pyyaml=6.0.3=py310h3406613_0
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=pyhd8ed1ab_0
  - sdl2=2.32.56=h54a6638_0
  - sdl3=3.2.26=h68140b3_0
  - shaderc=2025.4=h3e344bc_0
  - snappy=1.2.2=h03e3b7b_1
  - spirv-tools=2025.4=hb700be7_0
  - svt-av1=3.1.2=hecca717_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2022.3.0=h8d10470_1
  - tk=8.6.13=noxft_ha0e22de_103
  - typing_extensions=4.15.0=pyhcf101f3_0
  - urllib3=2.6.0=pyhd8ed1ab_0
  - wayland=1.24.0=hd6090a7_1
  - wayland-protocols=1.45=hd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - yaml=0.2.5=h280c20c_3
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.2.5=hde8ca8f_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - accelerate==0.18.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - asttokens==3.0.1
      - attrs==25.4.0
      - beautifulsoup4==4.14.3
      - cffi==1.17.1
      - click==8.3.1
      - cloudpickle==1.6.0
      - cmake==3.25.0
      - coloredlogs==15.0.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - daemoniker==0.2.3
      - decorator==5.2.1
      - dill==0.4.0
      - distro==1.9.0
      - dm-tree==0.1.9
      - einops==0.8.1
      - entmax==1.3
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastapi==0.124.0
      - flaky==3.8.1
      - fonttools==4.61.0
      - gdown==5.2.0
      - getch==1.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glcontext==3.0.0
      - glfw==1.12.0
      - gym==0.19.0
      - gym3==0.3.3
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - imagehash==4.3.2
      - imageio==2.37.2
      - imageio-ffmpeg==0.3.0
      - importlib-resources==6.5.2
      - inflection==0.5.1
      - iniconfig==2.3.0
      - ipython==8.37.0
      - jedi==0.19.2
      - jiter==0.12.0
      - jsonlines==4.0.0
      - kiwisolver==1.4.9
      - kornia==0.8.2
      - kornia-rs==0.1.10
      - lit==15.0.7
      - lxml==6.0.2
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mineclip==0.1
      - minedojo==0.1
      - minerl==1.0.0
      - moderngl==5.12.0
      - multiprocess==0.70.18
      - mypy-extensions==1.1.0
      - numpy==1.23.5
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - omegaconf==2.3.0
      - openai==2.9.0
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pexpect==4.9.0
      - pip==24.0
      - platformdirs==4.5.1
      - pluggy==1.6.0
      - praw==7.8.1
      - prawcore==2.4.0
      - protobuf==6.33.2
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyglet==2.1.11
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pyro4==4.82
      - pytest==9.0.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pywavelets==1.8.0
      - regex==2025.11.3
      - safetensors==0.7.0
      - scipy==1.15.3
      - sentry-sdk==2.47.0
      - serpent==1.42
      - setuptools==59.8.0
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - stack-data==0.6.3
      - starlette==0.50.0
      - tokenizers==0.22.1
      - tomli==2.3.0
      - torch==2.7.1+cu118
      - torchaudio==2.7.1+cu118
      - torchvision==0.22.1+cu118
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.3
      - triton==3.3.1
      - typing==3.7.4.3
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - update-checker==0.18.0
      - wandb==0.23.1
      - websocket-client==1.9.0
      - wget==3.2
      - wheel==0.37.1
      - wrapt==2.0.1
      - x-transformers==0.27.1
      - xmltodict==0.12.0
prefix: /users/PAS2926/inolan/miniconda/envs/steve1
